# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript



trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Application security testing@2020
  inputs:
    projectName: 'Test SCA'
    enableSastScan: true
    CheckmarxService: 'Cx-SAST'
    fullTeamName: 'CxServer'
    vulnerabilityThreshold: true
    high: '1'
    medium: '1'
    low: '1'
    enableDependencyScan: true
    dependencyServerURL: 'CxSCA'
    dependencyTenant: 'SCAPOC_Librity'
    scaVulnerabilityThreshold: true
    scaHigh: '1'
    scaMedium: '1'
    scaLow: '1'


- script: |
    npm install
    npm run
  displayName: 'npm install and build'
